### ISSUE TITLE
IndexOutOfBoundsException at Model:60

### ISSUE THREAD

**Issue by chiefwithbeef44** [chiefwithbeef44/machine_learning#4]
java.lang.IndexOutOfBoundsException: Index: 42000, Size: 42000
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at weka.core.Instances.get(Instances.java:821)
	at com.csp.model.Model.train(Model.java:60)
	at com.csp.Main.main(Main.java:87)

**Comment by chiefwithbeef44** [comment]
fixed by setting while loop in Model.train to max out at 41999 not 42000
